# Generated by Django 4.0.1 on 2022-01-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0002_alter_client_is_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('chairs', models.IntegerField(default=3)),
                ('inside', models.BooleanField(default=True)),
                ('availabDays', models.IntegerField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('clients', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.client')),
                ('tables', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tables.tables')),
            ],
        ),
    ]
