# Generated by Django 3.2.10 on 2022-01-21 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('chairs', models.IntegerField(default=3)),
                ('inside', models.BooleanField(default=True)),
                ('UnavailabDay', models.CharField(choices=[('', ''), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.client')),
                ('tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.table')),
            ],
            options={
                'unique_together': {('tables', 'time', 'date')},
            },
        ),
    ]
