# Generated by Django 3.2.10 on 2022-01-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='UnavailabDay',
            field=models.CharField(choices=[('None', 'None'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], default='', max_length=100),
        ),
    ]
