# Generated by Django 4.0.1 on 2022-01-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_client_is_vip'),
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tables',
            new_name='Table',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='TableOrder',
        ),
    ]
