# Generated by Django 3.2.10 on 2022-01-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_alter_table_unavailabday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableorder',
            old_name='clients',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='tableorder',
            old_name='tables',
            new_name='table',
        ),
        migrations.AlterUniqueTogether(
            name='tableorder',
            unique_together={('table', 'time', 'date')},
        ),
    ]
