# Generated by Django 4.0.1 on 2022-01-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_rename_tables_table_rename_orders_tableorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='availabDays',
            new_name='UnavailabDay',
        ),
    ]
