# Generated by Django 4.0.1 on 2022-01-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0003_rename_availabdays_table_unavailabday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='UnavailabDay',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], default=None, max_length=100),
        ),
    ]
