# Generated by Django 3.2.10 on 2022-01-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0003_auto_20220122_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableorder',
            old_name='client',
            new_name='clients',
        ),
        migrations.RenameField(
            model_name='tableorder',
            old_name='table',
            new_name='tables',
        ),
        migrations.AlterUniqueTogether(
            name='tableorder',
            unique_together={('tables', 'time', 'date')},
        ),
    ]
