# Generated by Django 4.0.1 on 2022-01-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0006_alter_tableorder_clients_alter_tableorder_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tableorder',
            unique_together={('tables', 'time', 'date')},
        ),
    ]
