# Generated by Django 4.0.1 on 2022-01-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0007_alter_tableorder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='UnavailabDay',
            field=models.CharField(choices=[('', ''), (6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday')], default='', max_length=100),
        ),
    ]
