# Generated by Django 4.0.1 on 2022-01-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0008_alter_table_unavailabday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='UnavailabDay',
            field=models.CharField(choices=[('', ''), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], default='', max_length=100),
        ),
    ]
