# Generated by Django 3.2.10 on 2022-01-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Is_VIP',
            field=models.BooleanField(default=False, verbose_name='VIP Client?'),
        ),
    ]
