# Generated by Django 3.2.10 on 2022-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_barista_orderstoprepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='coffeeCups',
            field=models.IntegerField(default=0),
        ),
    ]
