# Generated by Django 3.2.10 on 2022-01-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.client')),
                ('menuObjs', models.ManyToManyField(null=True, to='Menu.MenuObj')),
            ],
        ),
    ]
