# Generated by Django 3.2.10 on 2022-01-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0006_remove_menuobj_drink'),
        ('Authentication', '0002_alter_client_is_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.client')),
                ('menuObjs', models.ManyToManyField(to='Menu.MenuObj')),
            ],
        ),
    ]
