# Generated by Django 3.2.10 on 2022-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_remove_menuobj_drink'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menuObjs',
            field=models.ManyToManyField(blank=True, to='Menu.MenuObj'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
