# Generated by Django 3.2.10 on 2022-01-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_remove_menuobj_drink'),
        ('Cart', '0002_auto_20220120_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menuObjs',
            field=models.ManyToManyField(null=True, to='Menu.MenuObj'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
