# Generated by Django 3.2.10 on 2022-01-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='menu/images')),
                ('availability', models.BooleanField(default=True)),
                ('ageLimitation', models.BooleanField(default=False)),
                ('VIP', models.BooleanField(default=False)),
                ('morning', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('evning', models.BooleanField(default=True)),
                ('outside', models.BooleanField(default=True)),
                ('inside', models.BooleanField(default=True)),
                ('DOTD', models.BooleanField(default=False)),
                ('bought', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='Menu.categoryMenu')),
            ],
        ),
    ]
