# Generated by Django 4.0.1 on 2022-01-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_delete_spacielobj_alter_menuobj_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuobj',
            name='VIP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuobj',
            name='evning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuobj',
            name='inside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuobj',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuobj',
            name='morning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuobj',
            name='outside',
            field=models.BooleanField(default=False),
        ),
    ]
