# Generated by Django 4.0.1 on 2022-01-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_menuobj_vip_menuobj_evning_menuobj_inside_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuobj',
            name='spacial',
        ),
    ]
