# Generated by Django 4.0.1 on 2022-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_remove_menuobj_spacial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuobj',
            name='DOTD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuobj',
            name='bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuobj',
            name='drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuobj',
            name='evning',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuobj',
            name='inside',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuobj',
            name='lunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuobj',
            name='morning',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuobj',
            name='outside',
            field=models.BooleanField(default=True),
        ),
    ]
