# Generated by Django 4.0.1 on 2022-01-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_menuobj_dotd_menuobj_bought_menuobj_drink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuobj',
            name='drink',
        ),
    ]
