# Generated by Django 3.2.10 on 2022-01-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_remove_menuobj_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuobj',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
