# Generated by Django 3.2.10 on 2022-01-21 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_barista_orderstoprepare'),
        ('orders', '0002_auto_20220121_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.client'),
        ),
    ]
