# Generated by Django 3.2.10 on 2022-01-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
